name: flight_segment
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - xarray
  - requests
  - aiohttp
  - intake<2.0.0
  - intake-xarray
  - coloredlogs
  - bokeh
  - cartopy
  - hvplot
  - ipykernel
  - jupyter
  - pip
  - pyyaml
  - pip:
    - tqdm
    - orcestra
    - ipfsspec>=0.5.3
